baseURL = "https://blog.cecton.com"
languageCode = "en-us"
title = "cecton's blog"
theme = "m10c"

[params]
  author = "Cecile Tonglet"
  description = "🦀 Rustacean | Proud Internet rando"

  [[params.social]]
    name = "github"
    url = "https://github.com/cecton"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/CecileTonglet"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/cecton/"

  [params.style]
    primaryColor = "#da6565"
