[build.environment]
HUGO_VERSION = "0.54.0"

[build]
publish = "public"
command = "curl -sL https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.tar.gz | tar xvz && ./hugo --gc --minify"
